# Generated by Django 3.1.4 on 2021-01-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='body',
            new_name='phoneno',
        ),
    ]
