# Generated by Django 3.1.4 on 2021-02-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_auto_20210214_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_record', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='surgical_instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='staff_supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.employee')),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients_info', models.TextField()),
                ('app_date', models.DateField()),
                ('Receiptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.receiptionist')),
            ],
        ),
        migrations.CreateModel(
            name='prescribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testorPres', models.CharField(max_length=20)),
                ('Doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.doctors')),
                ('Prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noofbeds', models.IntegerField()),
                ('Room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check.room')),
            ],
        ),
    ]
