# Generated by Django 3.1.4 on 2021-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_furniture_pharmacy_prescribed_prescription_records_staff_supplies_surgical_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bill_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Bill',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='b_group',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='bill',
        ),
    ]
