# Generated by Django 3.1.4 on 2021-02-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0012_auto_20210214_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='allot_date',
        ),
    ]
